ncsc_cases_app/base_app/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

app_name = "base_app"
urlpatterns = [
    # Index URL
    path('', views.index, name='home'),

    # URLs for cases and cvd services

    path("cases/", include("cases_service.urls")),
    path("cvd/", include("cvd_service.urls")),

    path('cookie-consent/', views.cookie_consent, name='cookie_consent'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),

    path("admin/", admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('register/', views.register, name='register'),


]

ncsc_cases_app/cases_service/urls.py
from django.urls import path

from . import views
from .views import CaseListView, CaseCreateView

app_name = "cases_service"
urlpatterns = [

    path("", views.CaseListView.as_view(),
         name='case_list'),  # Cases service index
    # Case detail for a given case the user clicks on
    path('<int:pk>/', views.CaseDetailView.as_view(), name='case_detail'),
    # POST endpoint for when a user wants to delete a case
    path('<str:id>/delete/', views.delete_case, name='delete_case'),
    # POST endpoint for when a user wants to create a case
    path('create/', views.CaseCreateView.as_view(), name='create_case'),

]

ncsc_cases_app/ncsc_cases_application/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

ncsc_cases_app/cases_service/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Case(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.title

ncsc_cases_app/cases_service/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST
import logging
from django.contrib.auth.decorators import user_passes_test

from .models import Case

# Create a logger for this module
logger = logging.getLogger(__name__)


class CaseListView(generic.ListView):
    model = Case
    template_name = 'cases_service/case_list.html'
    context_object_name = 'cases'

    def get_queryset(self):
        """
        Get the queryset of all cases.

        Returns:
            QuerySet: All cases.
        """
        try:
            return Case.objects.all()
        except Exception as e:
            logger.exception("Error getting queryset in CaseListView: %s", e)
            return None


class CaseDetailView(generic.DetailView):
    model = Case
    template_name = 'cases_service/case_detail.html'
    context_object_name = 'case'

    def get_object(self, queryset=None):
        """
        Get the case object.

        Args:
            queryset (QuerySet, optional): The queryset from which the object is retrieved. Defaults to None.

        Returns:
            Case: The case object.

        Raises:
            Http404: If the case does not exist.
        """
        try:
            return super().get_object(queryset)
        except Http404 as e:
            logger.error("Case not found in CaseDetailView: %s", e)
            raise e
        except Exception as e:
            logger.exception("Error in CaseDetailView: %s", e)
            raise e


class CaseCreateView(LoginRequiredMixin, CreateView):
    model = Case
    fields = ['title', 'description']
    template_name = 'cases_service/create_case.html'
    success_url = reverse_lazy('cases_service:case_list')

    def form_valid(self, form):
        """
        Validate the case creation form.

        Args:
            form (Form): The case creation form.

        Returns:
            HttpResponse: The response indicating the success of the form validation.

        Raises:
            Exception: If there is an error in form validation.
        """
        try:
            form.instance.user = self.request.user
            return super().form_valid(form)
        except Exception as e:
            logger.exception(
                "Error in form validation in CaseCreateView: %s", e)
            return self.form_invalid(form)


@require_POST
@user_passes_test(lambda user: user.is_authenticated, login_url='/login/')
def delete_case(request, id):
    """
    Delete a case.

    Args:
        request (HttpRequest): The HTTP request.
        id (int): The ID of the case to be deleted.

    Returns:
        HttpResponse: The response indicating the success or failure of the case deletion.

    Raises:
        Http404: If the case does not exist.
    """
    try:
        case = Case.objects.get(id=id)
        case.delete()
        return redirect('cases_service:case_list')
    except Case.DoesNotExist as e:
        logger.error("Case to delete not found: %s", e)
        raise Http404("Case does not exist")
    except Exception as e:
        logger.exception("Error deleting case: %s", e)
        return HttpResponse(status=500)

ncsc_cases_app/cases_service/templates/cases_service/case_detail.html
{% extends 'base_app/base.html' %} {% block title %}Case Detail{% endblock %}
{%block content %}
<div class="container mx-auto py-8">
  <h1 class="text-3xl font-bold mb-4">Case Detail</h1>

  <div class="bg-white rounded-lg shadow-md p-8">
    <h2 class="text-xl font-bold mb-4">{{ case.title }}</h2>
    <p class="mb-4"><strong>Case ID:</strong> {{ case.id }}</p>
    <p class="mb-4"> <strong>Created by: </strong>{{ case.user.first_name }} {{ case.user.last_name }} </p>
    <p class="mb-4"><strong>Description:</strong> {{ case.description }}</p>
  </div>
</div>
{% endblock %}

ncsc_cases_app/cases_service/templates/cases_service/case_list.html
{% extends 'base_app/base.html' %} {% block title %}Case List{% endblock %}
{%block content %} {% if user.is_authenticated %}
<a
  href="{% url 'cases_service:create_case' %}"
  class="mb-4 inline-block py-2 px-4 bg-blue-500 text-white rounded hover:bg-blue-700"
>
  Create New Case
</a>
{% endif %}

<h1 class="text-2xl font-bold mb-4">Case List</h1>

{% if not cases %}
<p>There are no active cases.</p>
{% else %}
<table class="table-auto w-full">
  <thead>
    <tr>
      <th class="px-4 py-2">Case ID</th>
      <th class="px-4 py-2">Title</th>
      <th class="px-4 py-2">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for case in cases %}
    <tr>
      <td class="border px-4 py-2">{{ case.id }}</td>
      <td class="border px-4 py-2">{{ case.title }}</td>
      <td class="border px-4 py-2 flex items-center">
        {% if user.is_authenticated %}
        <form
          method="POST"
          action="{% url 'cases_service:delete_case' case.id %}"
        >
          {% csrf_token %}
          <button
            type="submit"
            class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-700"
          >
            Delete Case
          </button>
        </form>
        {% endif %}
        <a
          href="{% url 'cases_service:case_detail' case.id %}"
          class="ml-2 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-700"
        >
          View Case
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %} {% endblock %}

ncsc_cases_app/cases_service/templates/cases_service/create_case.html
{% extends 'base_app/base.html' %} {% block title %}Create Case{% endblock %}
{%block content %}
<h1 class="text-2xl font-bold mb-4">Create Case</h1>

<form method="POST" class="max-w-sm mx-auto">
  {% csrf_token %}
  <div class="mb-4">
    <label for="title" class="block text-gray-700">Title:</label>
    <input
      type="text"
      name="title"
      id="title"
      class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
      required
    />
  </div>

  <div class="mb-4">
    <label for="description" class="block text-gray-700">Description:</label>
    <textarea
      name="description"
      id="description"
      rows="4"
      class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
      required
    ></textarea>
  </div>

  <button
    type="submit"
    class="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-700"
  >
    Create
  </button>
</form>
{% endblock %}

ncsc_cases_app/cases_service/templates/cases_service/index.html
<h1>index</h1>

ncsc_cases_app/cases_service/templates/cases_service/results.html
{% comment %}
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize
    }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'cases:detail' question.id %}">Vote again?</a> {% endcomment %}