ncsc_cases_app/base_app/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

app_name = "base_app"
urlpatterns = [
    # Index URL
    path('', views.index, name='home'),

    # URLs for cases and cvd services

    path("cases/", include("cases_service.urls")),
    path("cvd/", include("cvd_service.urls")),

    path('cookie-consent/', views.cookie_consent, name='cookie_consent'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),

    path("admin/", admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('register/', views.register, name='register'),


]

ncsc_cases_app/cvd_service/urls.py
from django.urls import path

from . import views

app_name = "cvd_service"
urlpatterns = [
    path("", views.CVDListView.as_view(), name='cvd_list'),
    path('cvd/<int:pk>/', views.CVDDetailView.as_view(), name='cvd_detail'),
    path('cvd/<int:pk>/delete/', views.delete_cvd, name='delete_cvd'),
    path('create/', views.CVDCreateView.as_view(), name='create_cvd'),
]

ncsc_cases_app/cvd_service/models.py
from django.db import models
from django_cryptography.fields import encrypt


class CvdReport(models.Model):
    VULNERABILITY_TYPES = (
        ('injection', 'Injection'),
        ('broken_auth', 'Broken Authentication'),
        ('data_exposure', 'Sensitive Data Exposure'),
        ('xxe', 'XML External Entities (XXE)'),
        ('misconfigurations', 'Security Misconfigurations'),
        ('xss', 'Cross-Site Scripting (XSS)'),
        ('access_control', 'Broken Access Control'),
        ('insecure_deserialization', 'Insecure Deserialization'),
        ('availability', 'Availability'),
        ('integrity', 'Integrity'),
        ('confidentiality', 'Confidentiality'),
    )

    """
    Applicable reference(s):
    A3:2017-Sensitive Data Exposure

    """
    first_name = encrypt(models.CharField(
        max_length=100, blank=True, null=True))
    last_name = encrypt(models.CharField(
        max_length=100, blank=True, null=True))
    email = encrypt(models.EmailField())  # Email is required
    phone = encrypt(models.CharField(max_length=20, blank=True, null=True))
    vulnerability_type = models.CharField(
        max_length=30, choices=VULNERABILITY_TYPES)  # Vulnerability type is required
    explanation = models.TextField()  # Explanation is required
    vulnerability_reason = models.TextField()  # Reason is required
    domain_or_ip = models.TextField()  # Domain/IP is required
    pgp_key = encrypt(models.TextField())

    def __str__(self):
        return f"CVD Report #{self.pk}"

ncsc_cases_app/ncsc_cvd/models.py
from django.db import models


class CvdReport(models.Model):
    officer = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    VULNERABILITY_TYPES = (
        ('injection', 'Injection'),
        ('broken_auth', 'Broken Authentication'),
        ('data_exposure', 'Sensitive Data Exposure'),
        ('xxe', 'XML External Entities (XXE)'),
        ('misconfigurations', 'Security Misconfigurations'),
        ('xss', 'Cross-Site Scripting (XSS)'),
        ('access_control', 'Broken Access Control'),
        ('insecure_deserialization', 'Insecure Deserialization'),
        ('availability', 'Availability'),
        ('integrity', 'Integrity'),
        ('confidentiality', 'Confidentiality'),
    )
    vulnerability_type = models.CharField(
        max_length=30, choices=VULNERABILITY_TYPES)
    explanation = models.TextField()
    vulnerability_reason = models.TextField()
    domain_or_ip = models.TextField()
    pgp_key = models.TextField()

    def __str__(self):
        return f"CVD Report #{self.pk}"

ncsc_cases_app/cvd_service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django import forms


from django.urls import reverse_lazy
from django.views import generic
from .models import CvdReport
from django.utils import timezone
import logging

logger = logging.getLogger(__name__)

# Create your views here.


class CVDListView(LoginRequiredMixin, generic.ListView):
    model = CvdReport
    template_name = 'cvd_service/cvd_list.html'
    context_object_name = 'cvd_list'

    def get_queryset(self):
        # Return all CvdReport objects
        try:
            return CvdReport.objects.all()
        except Exception as e:
            logger.error('Error in CVDListView.get_queryset: %s', e)
            raise


class CVDDetailView(LoginRequiredMixin, generic.DetailView):
    model = CvdReport
    template_name = 'cvd_service/cvd_detail.html'


class CvdReportForm(forms.ModelForm):
    class Meta:
        model = CvdReport
        fields = ['first_name', 'last_name', 'email', 'phone', 'vulnerability_type',
                  'explanation', 'vulnerability_reason', 'domain_or_ip', 'pgp_key']

    def __init__(self, *args, **kwargs):
        super(CvdReportForm, self).__init__(*args, **kwargs)

        input_class = 'appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500'
        textarea_class = 'appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500'

        self.fields['first_name'].widget.attrs.update({'class': input_class})
        self.fields['last_name'].widget.attrs.update({'class': input_class})
        self.fields['email'].widget.attrs.update({'class': input_class})
        self.fields['phone'].widget.attrs.update({'class': input_class})
        self.fields['vulnerability_type'].widget.attrs.update(
            {'class': input_class})
        self.fields['explanation'].widget.attrs.update(
            {'class': textarea_class})
        self.fields['vulnerability_reason'].widget.attrs.update(
            {'class': textarea_class})
        self.fields['domain_or_ip'].widget.attrs.update(
            {'class': textarea_class})
        self.fields['pgp_key'].widget.attrs.update({'class': textarea_class})


class CVDCreateView(generic.CreateView):
    model = CvdReport
    form_class = CvdReportForm
    template_name = 'cvd_service/create_cvd.html'
    success_url = reverse_lazy('cvd_service:create_cvd')


@require_POST
def delete_cvd(request, pk):
    try:
        cvd = get_object_or_404(CvdReport, pk=pk)
        cvd.delete()
        # Redirect the user to the CVD list view after deleting
        return redirect('cvd_service:cvd_list')
    except Exception as e:
        logger.error('Error in delete_cvd: %s', e)
        raise

ncsc_cases_app/cvd_service/templates/cvd_service/create_cvd.html
{% extends 'base_app/base.html' %} {% block title %}Create CVD{% endblock %}
{%block content %}
<div class="container mx-auto py-5">
  <h1 class="text-3xl mb-4">Create CVD Report</h1>
  <form
    class="bg-white w-full rounded-lg shadow-lg p-8"
    method="POST"
    action="{% url 'cvd_service:create_cvd' %}"
  >
    {% csrf_token %}
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_first_name"
        >First Name</label
      >
      {{ form.first_name }}
    </div>
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_last_name"
        >Last Name</label
      >
      {{ form.last_name }}
    </div>
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="id_email"
        >Email</label
      >
      {{ form.email }}
    </div>
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="id_phone"
        >Phone</label
      >
      {{ form.phone }}
    </div>
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_vulnerability_type"
        >Vulnerability Type</label
      >
      {{ form.vulnerability_type }}
    </div>
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_explanation"
        >Explanation</label
      >
      {{ form.explanation }}
    </div>
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_vulnerability_reason"
        >Vulnerability Reason</label
      >
      {{ form.vulnerability_reason }}
    </div>
    <div class="mb-4">
      <label
        class="block text-gray-700 text-sm font-bold mb-2"
        for="id_domain_or_ip"
        >Domain or IP</label
      >
      {{ form.domain_or_ip }}
    </div>
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="id_pgp_key"
        >PGP Key</label
      >
      {{ form.pgp_key }}
    </div>
    <div class="flex items-center justify-between">
      <button
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        type="submit"
      >
        Submit
      </button>
    </div>
  </form>
</div>
{% endblock %}

ncsc_cases_app/cvd_service/templates/cvd_service/cvd_detail.html
{% extends 'base_app/base.html' %} {% block title %}CVD Detail{% endblock %}
{%block content %}
<h1>CVD Detail</h1>
<p>Officer: {{ object.officer }}</p>
<p>First Name: {{ object.first_name }}</p>
<p>Last Name: {{ object.last_name }}</p>
<p>Email: {{ object.email }}</p>
<p>Phone: {{ object.phone }}</p>
<p>Vulnerability Type: {{ object.get_vulnerability_type_display }}</p>
<p>Explanation: {{ object.explanation }}</p>
<p>Vulnerability Reason: {{ object.vulnerability_reason }}</p>
<p>Domain or IP: {{ object.domain_or_ip }}</p>
<p>PGP Key: {{ object.pgp_key }}</p>

<!-- Delete Button -->
<form action="{% url 'cvd_service:delete_cvd' object.id %}" method="POST">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

{% endblock %}

ncsc_cases_app/cvd_service/templates/cvd_service/cvd_list.html
{% extends 'base_app/base.html' %} {% block title %} CVD Report List
{%endblock%} {% block content %}
<div class="container mx-auto px-4 sm:px-8">
  <div class="py-8">
    <h2 class="text-2xl font-semibold leading-tight">CVD Report List</h2>
    <div class="my-2 flex sm:flex-row flex-col">
      <a
        href="{% url 'cvd_service:create_cvd' %}"
        class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >Create New CVD</a
      >
    </div>

    {% if not cvd_list %}
    <p>There are no active CVD reports.</p>
    {% else %} {% for cvd in cvd_list %}
    <div class="py-2">
      <div class="flex flex-col border-2 rounded-lg p-4 bg-white">
        <p><strong>First Name:</strong> {{ cvd.first_name }}</p>
        <p><strong>Last Name:</strong> {{ cvd.last_name }}</p>
        <p><strong>Email:</strong> {{ cvd.email }}</p>
        <p><strong>Phone:</strong> {{ cvd.phone }}</p>
        <p><strong>Vulnerability Type:</strong> {{ cvd.vulnerability_type }}</p>
        <p><strong>Explanation:</strong> {{ cvd.explanation }}</p>
        <p><strong>Reason:</strong> {{ cvd.vulnerability_reason }}</p>
        <p><strong>Domain/IP:</strong> {{ cvd.domain_or_ip }}</p>
        <p><strong>PGP Key:</strong> {{ cvd.pgp_key }}</p>

        {% if user.is_authenticated %}
        <div class="flex justify-between">
          <a
            href="{% url 'cvd_service:cvd_detail' cvd.id %}"
            class="text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg"
            >View</a
          >
          <form
            method="POST"
            action="{% url 'cvd_service:delete_cvd' cvd.id %}"
          >
            {% csrf_token %}
            <button
              type="submit"
              class="text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg"
            >
              Delete
            </button>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
</div>
{% endblock %}