ncsc_cases_app/base_app/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

app_name = "base_app"
urlpatterns = [
    # Index URL
    path('', views.index, name='home'),

    # URLs for cases and cvd services

    path("cases/", include("cases_service.urls")),
    path("cvd/", include("cvd_service.urls")),

    path('cookie-consent/', views.cookie_consent, name='cookie_consent'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),

    path("admin/", admin.site.urls),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    path('register/', views.register, name='register'),


]

ncsc_cases_app/cases_service/urls.py
from django.urls import path

from . import views
from .views import CaseListView, CaseCreateView

app_name = "cases_service"
urlpatterns = [

    path("", views.CaseListView.as_view(),
         name='case_list'),  # Cases service index
    # Case detail for a given case the user clicks on
    path('<int:pk>/', views.CaseDetailView.as_view(), name='case_detail'),
    # POST endpoint for when a user wants to delete a case
    path('<str:id>/delete/', views.delete_case, name='delete_case'),
    # POST endpoint for when a user wants to create a case
    path('create/', views.CaseCreateView.as_view(), name='create_case'),

]

ncsc_cases_app/cvd_service/urls.py
from django.urls import path

from . import views

app_name = "cvd_service"
urlpatterns = [
    path("", views.CVDListView.as_view(), name='cvd_list'),
    path('cvd/<int:pk>/', views.CVDDetailView.as_view(), name='cvd_detail'),
    path('cvd/<int:pk>/delete/', views.delete_cvd, name='delete_cvd'),
    path('create/', views.CVDCreateView.as_view(), name='create_cvd'),
]

ncsc_cases_app/base_app/views.py
from django.views.generic import TemplateView
from django.http import JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.auth.views import LogoutView as AuthLogoutView
from django.core.cache import cache
from django.conf import settings

import logging
from django.shortcuts import render, redirect

logger = logging.getLogger(__name__)


class LoginView(AuthLoginView):
    def form_invalid(self, form):
        """
        Handle the form submission when the form is invalid (failed login attempt).

        This method is called when the form data is invalid, i.e., the username or password is incorrect.
        It logs the failed login attempt and checks if the user has exceeded the maximum login attempts.
        If the user has exceeded the maximum login attempts, it performs IP blocking logic, sets a flag in the session
        to display the banner, logs a warning about the user being blocked, and redirects the user to the login page.
        If the user has not exceeded the maximum login attempts, it increments the login attempts counter in the cache,
        logs the failed login attempt, and renders the response with the form errors.

        Applicable reference(s):
        A07:2021 – Identification and Authentication Failures

        """

        username = self.request.POST.get('username')
        ip = get_client_ip(self.request)
        cache_key = f"login_attempts:{ip}"
        login_attempts = cache.get(cache_key, 0)

        # Check if the user has reached the maximum login attempts
        if login_attempts >= 5:
            # IP blocking logic
            # Set a flag in the session to display the banner
            self.request.session['login_attempts_exceeded'] = True

            # Log a warning indicating that the user has been blocked
            logger.warning(
                'User blocked due to exceeded login attempts - Username: %s, IP address: %s',
                username,
                ip
            )

            # Redirect the user to the login page
            return redirect('login')

        # Increment the login attempts counter
        cache.set(cache_key, login_attempts + 1,
                  settings.LOGIN_ATTEMPTS_CACHE_TIMEOUT)

        try:
            logger.warning(
                'Failed login attempt - Username: %s, IP address: %s',
                username,
                ip
            )
        except Exception as e:
            logger.error('Error in LoginView.form_invalid: %s', e)

        return self.render_to_response(self.get_context_data(form=form))


class LogoutView(AuthLogoutView):
    def dispatch(self, request, *args, **kwargs):
        """
        Handle the user logout.

        This method is called when the user logs out. It logs the username and IP address of the user who logged out.
        """
        try:
            username = self.request.user.username
            ip = get_client_ip(self.request)
            logger.info(
                'User logged out - Username: %s, IP address: %s',
                username,
                ip
            )
        except Exception as e:
            logger.error('Error in LogoutView.dispatch: %s', e)
        return super().dispatch(request, *args, **kwargs)


def get_client_ip(request):
    """
    Get the client IP address from the request.

    This function retrieves the client's IP address from the request's META data.
    It checks if the request contains an X-Forwarded-For header and extracts the first IP address from the list.
    If the X-Forwarded-For header is not present, it retrieves the IP address provided by Django.

    Returns:
    - The client IP address.
    """
    try:
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            # if it is a list, take the first IP
            ip = x_forwarded_for.split(',')[0]
        else:
            # else take the IP provided by Django
            ip = request.META.get('REMOTE_ADDR')
    except Exception as e:
        logger.error('Error in get_client_ip: %s', e)
        ip = None
    return ip


def index(request):
    """
    Render the index page.

    This view renders the index page.
    """
    try:
        return render(request, 'base_app/index.html')
    except Exception as e:
        logger.error('Error in index view: %s', e)
        raise


def register(request):
    """
    Handle user registration.

    This view handles the user registration process.
    If the request method is POST, it validates the registration form.
    If the form is valid, it saves the user and redirects to the login page.
    If the form is not valid, it renders the registration form with the form errors.

    Applicable reference(s):
    OAT-019 Account Creation
    """
    try:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('login')
        else:
            form = UserCreationForm()
        return render(request, 'registration/register.html', {'form': form})
    except Exception as e:
        logger.error('Error in register view: %s', e)


def cookie_consent(request):
    """
    Set the cookie consent flag.

    This view sets the cookie consent flag in the user's session.
    It returns a JSON response with the status 'ok'.

    Applicable reference(s):
    https://gdpr.eu/cookies/
    """
    request.session['cookie_consent'] = True
    return JsonResponse({'status': 'ok'})


def privacy_policy(request):
    """
    Render the privacy policy page.

    This view renders the privacy policy page.
    """
    return render(request, 'base_app/privacy_policy.html')

ncsc_cases_app/base_app/templates/base_app/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Add your CSS and other common headers here -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <!-- Cookie Consent Popup -->
    {% if not request.session.cookie_consent %}
    <div
      id="cookie-popup"
      class="fixed bottom-0 left-0 w-full bg-blue-500 text-white py-3 px-6 flex items-center justify-between"
    >
      <p>
        We use cookies to improve your experience. By using our site, you agree
        to our use of cookies.
      </p>
      <button
        id="cookie-consent-button"
        class="bg-white text-blue-500 px-4 py-2 rounded"
      >
        I Agree
      </button>
    </div>
    <script>
      document
        .getElementById("cookie-consent-button")
        .addEventListener("click", function () {
          fetch("{% url 'cookie_consent' %}", {
            method: "POST",
            headers: {
              "Content-Type": "application/x-www-form-urlencoded",
              "X-CSRFToken": "{{ csrf_token }}",
            },
          })
            .then((response) => {
              if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
              }
              return response.json();
            })
            .then((json) => {
              document.getElementById("cookie-popup").style.display = "none";
            })
            .catch((e) => {
              console.log(
                "There has been a problem with the fetch operation: " +
                  e.message
              );
            });
        });
    </script>
    {% endif %}
    <!-- End Cookie Consent Popup -->

    <nav class="bg-white border-gray-200 dark:bg-gray-900">
      <div
        class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4"
      >
        <a href="{% url 'home' %}" class="flex items-center">
          <img
            src="https://allvectorlogo.com/img/2019/08/national-cyber-security-centre-ncsc-logo-vector.png"
            class="h-20 mr-3"
            alt="Logo"
          />
        </a>

        <button
          data-collapse-toggle="navbar-default"
          type="button"
          class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
          aria-controls="navbar-default"
          aria-expanded="false"
        >
          <span class="sr-only">Open main menu</span>
          <svg
            class="w-5 h-5"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 17 14"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 1h15M1 7h15M1 13h15"
            />
          </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-default">
          <ul
            class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
          >
            <li>
              <a
                href="{% url 'home' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >Home</a
              >
            </li>
            {% if user.is_authenticated %}
            <li>
              <a
                href="{% url 'cvd_service:cvd_list' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >CVD module</a
              >
            </li>
            <li>
              <a
                href="{% url 'cases_service:case_list' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >Cases module</a
              >
            </li>
            {% else %}
            <li>
              <a
                href="{% url 'cvd_service:create_cvd' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >Submit CVD Report</a
              >
            </li>
            <li>
              <a
                href="{% url 'cases_service:case_list' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >View all active cases</a
              >
            </li>
            {% endif %} {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            <li>
              <a
                href="{% url 'privacy_policy' %}"
                class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500"
                aria-current="page"
                >Privacy Policy</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <main class="container mx-auto pt-12">
      {% block content %} {% endblock %}
    </main>

    <footer>
      <!-- Add your footer content here -->
    </footer>

    <!-- Add your JavaScript and other common scripts here -->
  </body>
</html>

ncsc_cases_app/base_app/templates/base_app/index.html
{% extends 'base_app/base.html' %} {% block title %}Main page{% endblock %}
{%block content %}

<div class="flex flex-col items-center justify-center h-screen bg-gray-100">
  <div class="bg-white rounded-lg p-8 shadow-lg mb-8">
    <img
      src="https://allvectorlogo.com/img/2019/08/national-cyber-security-centre-ncsc-logo-vector.png"
      class="h-40"
      alt="Logo"
    />
  </div>

  <h1 class="text-4xl font-bold mb-4 text-center">
    Welcome to the Dutch National Cybersecurity Centre Cybercrime Repository
  </h1>

  <div class="bg-white rounded-lg p-8 shadow-lg">
    {% if user.is_authenticated %}
    <h2 class="text-2xl mb-4">
      Welcome, {{ user.first_name }} {{ user.last_name }}!
    </h2>
    <p>Last Login: {{ user.last_login }}</p>
    {% else %}
    <p class="text-center">
      If you are an NCSC officer, please
      <a href="{% url 'login' %}" class="text-blue-500 underline">Login</a>
    </p>
    <p class="text-center">
      If you are a civilian, please use the buttons below or the navigation bar
    </p>
    {% endif %}
  </div>

  <div class="mt-8 space-x-4">
    {% if user.is_authenticated %}
    <a
      href="{% url 'cvd_service:cvd_list' %}"
      class="rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold hover:bg-indigo-500"
    >
      Go to CVD page
    </a>
    {% else %}
    <a
      href="{% url 'cvd_service:create_cvd' %}"
      class="rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold hover:bg-indigo-500"
    >
      Submit Coordinated Vulnerability Disclosure Report
    </a>
    {% endif %}
    <a
      href="{% url 'cases_service:case_list' %}"
      class="rounded-md bg-indigo-600 px-4 py-2 text-white font-semibold hover:bg-indigo-500"
    >
      View list of currently active cases
    </a>
  </div>
</div>

{% endblock %}

ncsc_cases_app/base_app/templates/base_app/privacy_policy.html
{% extends "base_app/base.html" %}

{% block content %}
<div class="max-w-screen-md mx-auto my-10">
    <h1 class="text-2xl font-bold mb-5">Privacy Policy</h1>

    <h2 class="text-xl font-semibold my-3">1. Who are we?</h2>
    <p>
        We are the National Cyber Security Centre of the Netherlands (NCSC-NL). Our postal address is PO box 20301, 2500 EH The Hague, The Netherlands, and our visiting address is Turfmarkt 147, 2511 DP The Hague, The Netherlands. Please note that ID is mandatory when visiting the NCSC.
        You can contact us by post at the above postal address, by email at info@ncsc.nl, or by telephone at +31 70 751 55 55.
    </p>

    <h2 class="text-xl font-semibold my-3">2. What information do we collect?</h2>
    <p>
        We collect and process the following information which may include your personal data.
        <ul class="list-disc list-inside">
            <li>Full name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <!-- Add any other data points your app collects -->
        </ul>
    </p>

    <h2 class="text-xl font-semibold my-3">3. Why do we collect this information?</h2>
    <p>
        We will use your information to respond to any enquiries you make or to handle the reports you submit. This processing is necessary 
        in order to take steps at your request prior to entering into a contract.
    </p>

    <h2 class="text-xl font-semibold my-3">4. What do we do with your information?</h2>
    <p>
        Your information is stored in our database and is not shared with any third parties, 
        except for those necessary to process your requests. We do not use the information provided 
        to make any automated decisions that might affect you.
    </p>

    <h2 class="text-xl font-semibold my-3">5. How long do we keep your information?</h2>
    <p>
        We keep your information unless you request us to delete it sooner.
    </p>

    <h2 class="text-xl font-semibold my-3">6. Your rights over your information</h2>
    <p>
        By law, you can ask us what information we hold about you, and you can ask us to correct it 
        if it is inaccurate. You can also ask us to give you a copy of the information and to stop using 
        your information for a period of time if you believe we are not doing so lawfully.
    </p>

    <p>
        To submit a request by email, post or telephone, please use the contact information provided above.
    </p>

    <h2 class="text-xl font-semibold my-3">7. Your right to complain</h2>
    <p>
        If you have a complaint about our use of your information, you can contact the Data Protection Authority in the Netherlands (Autoriteit Persoonsgegevens) via their website at www.autoriteitpersoonsgegevens.nl or write to them at: Autoriteit Persoonsgegevens, Postbus 93374, 2509 AJ DEN HAAG.
    </p>
</div>
{% endblock %}